---
title: "Statistical Inference Project: A simulation exercise"
author: "Paul Reiners"
date: "January 18, 2015"
output: html_document
---

Exponential distribution CLT
----------------------------

Compare the distribution of 1000 exponentials

```{r}
lambda <- 0.2
n <- 1000
hist(rexp(n, lambda))
```

and the distribution of 1000 averages of 40 exponentials

```{r}
mns = NULL
for (i in 1 : 1000) mns = c(mns, mean(rexp(40, lambda)))
hist(mns)
```

Notice how the distribution of the 1000 **averages** of random exponentials appears to be approximately normal.  Also note that its mean appears to be the mean of the 1000 generated random exponentials.

Sample and theoretical means
----------------------------

What is the sample mean of the distribution?

```{r}
sample.mean <- mean(mns)
sample.mean
```

The theoretical mean of the exponential distribution is 1/lambda:

```{r}
theoretical.mean <- 1/lambda
theoretical.mean
```

They differ by less than 1%:

```{r}
abs(sample.mean - theoretical.mean) / theoretical.mean
```

Sample and theoretical variances
--------------------------------

What is the sample variance of the distribution?

```{r}
vars = NULL
for (i in 1 : 1000) vars = c(vars, var(rexp(40, lambda)))
sample.var <- mean(vars)
sample.var
```

The theoretical standard deviation of the exponential distribution is 1/lambda.  So the variance is the square of this:

```{r}
theoretical.var <- (1/lambda)^2
theoretical.var
```

They also differ by less than 1%:

```{r}
abs(sample.var - theoretical.var) / theoretical.var
```

Distribution is approximately normal
------------------------------------

We now illustrate that the distribution is approximately normal.

```{r}
library("ggplot2")
nosim <- 1000
cfunc <- function(x, n) sqrt(n) * (mean(x) - theoretical.mean) / sqrt(theoretical.var) 
dat <- data.frame(
  x = c(apply(matrix(rexp(nosim * 10, lambda), 
                     nosim), 1, cfunc, 10),
        apply(matrix(rexp(nosim * 20, lambda), 
                     nosim), 1, cfunc, 20),
        apply(matrix(rexp(nosim * 30, lambda), 
                     nosim), 1, cfunc, 30)
        ),
  size = factor(rep(c(10, 20, 30), rep(nosim, 3))))
g <- ggplot(dat, aes(x = x, fill = size)) + geom_histogram(binwidth=.3, colour = "black", aes(y = ..density..)) 
g <- g + stat_function(fun = dnorm, size = 2)
g + facet_grid(. ~ size)
```
